// Interface automatically generated by schemas-to-ts

import { MenuItem } from '../../../menu-item/content-types/menu-item/menu-item';
import { SocialLink } from '../../../social-link/content-types/social-link/social-link';
import { Media } from '../../../../common/schemas-to-ts/Media';
import { MenuItem_Plain } from '../../../menu-item/content-types/menu-item/menu-item';
import { SocialLink_Plain } from '../../../social-link/content-types/social-link/social-link';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Sidebar {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    menu_items: { data: MenuItem[] };
    social_links: { data: SocialLink[] };
    title?: string;
    subTitle?: string;
    image?: { data: Media };
  };
}
export interface Sidebar_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  menu_items: MenuItem_Plain[];
  social_links: SocialLink_Plain[];
  title?: string;
  subTitle?: string;
  image?: Media_Plain;
}

export interface Sidebar_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  menu_items: number[];
  social_links: number[];
  title?: string;
  subTitle?: string;
  image?: number;
}

export interface Sidebar_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  menu_items: AdminPanelRelationPropertyModification<MenuItem_Plain>;
  social_links: AdminPanelRelationPropertyModification<SocialLink_Plain>;
  title?: string;
  subTitle?: string;
  image?: AdminPanelRelationPropertyModification<Media_Plain>;
}
