// Interface automatically generated by schemas-to-ts

export interface Faq {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    question?: string;
    answer?: string;
    Icon?: string;
  };
}
export interface Faq_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  question?: string;
  answer?: string;
  Icon?: string;
}

export interface Faq_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  question?: string;
  answer?: string;
  Icon?: string;
}

export interface Faq_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  question?: string;
  answer?: string;
  Icon?: string;
}
