// Interface automatically generated by schemas-to-ts

import { Card } from '../../elements/interfaces/Card';
import { Card_Plain } from '../../elements/interfaces/Card';
import { Card_NoRelations } from '../../elements/interfaces/Card';

export interface TitleAndCards {
  card: Card[];
  title?: string;
}
export interface TitleAndCards_Plain {
  card: Card_Plain[];
  title?: string;
}

export interface TitleAndCards_NoRelations {
  card: Card_NoRelations[];
  title?: string;
}

