// Interface automatically generated by schemas-to-ts

export interface TitleAndServices {
  title?: string;
  text?: string;
}
export interface TitleAndServices_Plain {
  title?: string;
  text?: string;
}

export interface TitleAndServices_NoRelations {
  title?: string;
  text?: string;
}

