// Interface automatically generated by schemas-to-ts

import { Card } from '../../elements/interfaces/Card';
import { Card_Plain } from '../../elements/interfaces/Card';
import { Card_NoRelations } from '../../elements/interfaces/Card';

export interface TitleAndCards {
  title?: string;
  card: Card[];
}
export interface TitleAndCards_Plain {
  title?: string;
  card: Card_Plain[];
}

export interface TitleAndCards_NoRelations {
  title?: string;
  card: Card_NoRelations[];
}

