// Interface automatically generated by schemas-to-ts

export interface SocialLink {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    iconName?: string;
    link?: string;
  };
}
export interface SocialLink_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  iconName?: string;
  link?: string;
}

export interface SocialLink_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  iconName?: string;
  link?: string;
}

export interface SocialLink_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  iconName?: string;
  link?: string;
}
