// Interface automatically generated by schemas-to-ts

import { Faq } from '../../../faq/content-types/faq/faq';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { Faq_Plain } from '../../../faq/content-types/faq/faq';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface FaqPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    pageTitle?: string;
    pageDescription?: string;
    faqTitle?: string;
    faqs: { data: Faq[] };
    seo?: Seo;
  };
}
export interface FaqPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageTitle?: string;
  pageDescription?: string;
  faqTitle?: string;
  faqs: Faq_Plain[];
  seo?: Seo_Plain;
}

export interface FaqPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageTitle?: string;
  pageDescription?: string;
  faqTitle?: string;
  faqs: number[];
  seo?: Seo_NoRelations;
}

export interface FaqPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  pageTitle?: string;
  pageDescription?: string;
  faqTitle?: string;
  faqs: AdminPanelRelationPropertyModification<Faq_Plain>;
  seo?: Seo_Plain;
}
