// Interface automatically generated by schemas-to-ts

import { TitleAndServices } from '../../../../components/blocks/interfaces/TitleAndServices';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { TitleAndServices_Plain } from '../../../../components/blocks/interfaces/TitleAndServices';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { TitleAndServices_NoRelations } from '../../../../components/blocks/interfaces/TitleAndServices';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';

export interface ServicesPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    services: TitleAndServices[];
    pageTitle?: string;
    seo?: Seo;
  };
}
export interface ServicesPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  services: TitleAndServices_Plain[];
  pageTitle?: string;
  seo?: Seo_Plain;
}

export interface ServicesPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  services: TitleAndServices_NoRelations[];
  pageTitle?: string;
  seo?: Seo_NoRelations;
}

export interface ServicesPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  services: TitleAndServices_Plain[];
  pageTitle?: string;
  seo?: Seo_Plain;
}
