// Interface automatically generated by schemas-to-ts

import { TitleAndCards } from '../../../../components/blocks/interfaces/TitleAndCards';
import { Seo } from '../../../../components/shared/interfaces/Seo';
import { TitleAndCards_Plain } from '../../../../components/blocks/interfaces/TitleAndCards';
import { Seo_Plain } from '../../../../components/shared/interfaces/Seo';
import { TitleAndCards_NoRelations } from '../../../../components/blocks/interfaces/TitleAndCards';
import { Seo_NoRelations } from '../../../../components/shared/interfaces/Seo';

export interface PortfolioPage {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title?: string;
    websites: TitleAndCards[];
    seo?: Seo;
  };
}
export interface PortfolioPage_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  websites: TitleAndCards_Plain[];
  seo?: Seo_Plain;
}

export interface PortfolioPage_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  websites: TitleAndCards_NoRelations[];
  seo?: Seo_NoRelations;
}

export interface PortfolioPage_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title?: string;
  websites: TitleAndCards_Plain[];
  seo?: Seo_Plain;
}
