// Interface automatically generated by schemas-to-ts

export interface FaqItem {
  questtion?: string;
  answer?: string;
}
export interface FaqItem_Plain {
  questtion?: string;
  answer?: string;
}

export interface FaqItem_NoRelations {
  questtion?: string;
  answer?: string;
}

