// Interface automatically generated by schemas-to-ts

export interface PriceBlockOption {
  title?: string;
  price?: number;
  description?: string;
}
export interface PriceBlockOption_Plain {
  title?: string;
  price?: number;
  description?: string;
}

export interface PriceBlockOption_NoRelations {
  title?: string;
  price?: number;
  description?: string;
}

