// Interface automatically generated by schemas-to-ts

import { PriceBlockOption } from './PriceBlockOption';
import { PriceBlockOption_Plain } from './PriceBlockOption';
import { PriceBlockOption_NoRelations } from './PriceBlockOption';

export interface PricebBlock {
  blockTitle?: string;
  option: PriceBlockOption[];
}
export interface PricebBlock_Plain {
  blockTitle?: string;
  option: PriceBlockOption_Plain[];
}

export interface PricebBlock_NoRelations {
  blockTitle?: string;
  option: PriceBlockOption_NoRelations[];
}

